### ISSUE TITLE
case sensitive problem

### ISSUE THREAD

**Issue by FranciscoBeccuti** [flame-engine/trex-flame#3]
Hi.
Thanks for the example.
In linux I find the following problems of file names.
lib / game / collision / collision_utils.dart
import 'package: trex / game / game.dart';
to
import 'package: trex / game / Game.dart';

lib / game / Game.dart
import 'package: trex / game / Horizon / horizon.dart';
to
import 'package: trex / game / horizon / horizon.dart';

lib / main.dart
import 'package: trex / game / game.dart';
to
import 'package: trex / game / Game.dart';

regards

**Comment by FranciscoBeccuti** [comment]
sorry, key = case

**Comment by renancaraujo** [comment]
Solved
