### ISSUE TITLE
Not compatible with Flame 0.16.1?

### ISSUE THREAD

**Issue by buttonsrtoys** [flame-engine/trex-flame#4]
pubspec.yaml doesn't list the current flame engine (0.16.1), instead using 

     flame:
        path: ../../contrib/flame

Changing it to 0.16.1 and updating a mixins path results in two errors in a half dozen class declarations. E.g., 

    class GameOverPanel extends PositionComponent
        with Resizable, ComposedComponent {

Gives two errors:

    Missing concrete implementations of Tapable.checkTapOverlap, Tapable.handleTapCancel, 
        Tapable.handleTapDown, Tapable.handleTapUp and 5 more.
        Try implementing the missing methods, or make the class abstract.

    'ComposedComponent' can't be mixed onto 'PositionComponent' because 
        'PositionComponent' doesn't implement 'HasGameRef<Game>'.
        Try extending the class 'ComposedComponent'.

Same errors at class CloudManager, HorizonLine, Horizon, ObstacleManager, and TRex.

**Comment by renancaraujo** [comment]
Yeah, we haven't updated this code for a while. Lets put that on our roadmap.

**Comment by buttonsrtoys** [comment]
Thanks for the update Renan. I don't mind taking a crack at this in a PR, but am new to Flame. Based on these two errors, can you make a suggestion on how to proceed?

**Comment by renancaraujo** [comment]
It was fixed on #5, thanks!
Let me knoew if you have any problem.
