### ISSUE TITLE
Internal error: (java.lang.ClassNotFoundException) com.google.wireless.android.sdk.stats.IntellijIndexingStats

### ISSUE THREAD

**Issue by Akshshr** [flame-engine/trex-flame#7]
Really cool project and I am trying to get this to build right now. 

Seeing something that isn't even part of the project I suppose. 

Any clue on how to solve this? 

<img width="1080" alt="Screenshot 2020-03-16 at 15 34 59" src="https://user-images.githubusercontent.com/11215286/76745480-ece14700-679b-11ea-9a79-9b00cb15770a.png">

**Comment by renancaraujo** [comment]
Try removing the android directory and running `flutter create .` on the project root.

**Comment by Akshshr** [comment]
Thanks for the quick reply! 

Hmm that took me a step ahead, now it says there is an issue with the pubspec.yaml file

<img width="1080" alt="Screenshot 2020-03-16 at 17 05 06" src="https://user-images.githubusercontent.com/11215286/76754590-6848f580-67a8-11ea-98ec-fd38a02a6b08.png">
